/**
 * THE ABI LIVES IN ONE PLACE: the compiled artifact. This writes it into TypeScript so the
 * app can read it, and `lib/payroll-abi.test.ts` regenerates and compares, so the contract
 * and the app cannot drift apart without a test going red.
 *
 *   npx tsx scripts/sync-abi.ts          write lib/payroll-abi.ts
 *   npx tsx scripts/sync-abi.ts --check  exit 1 if it is out of date
 */
import {readFileSync, writeFileSync} from "node:fs";

const SOURCES = [
  {artifact: "contracts/out/Payroll.sol/Payroll.json", name: "payrollAbi"},
] as const;

const HEADER = `// GENERATED BY scripts/sync-abi.ts — DO NOT EDIT BY HAND.
// The source of truth is the compiled artifact under contracts/out. Run:
//     cd contracts && forge build && cd .. && npx tsx scripts/sync-abi.ts
`;

export function render(): string {
  const parts = [HEADER];
  for (const s of SOURCES) {
    const {abi} = JSON.parse(readFileSync(s.artifact, "utf8")) as {abi: unknown[]};
    parts.push(`\nexport const ${s.name} = ${JSON.stringify(abi, null, 2)} as const;\n`);
  }
  return parts.join("");
}

if (process.argv[1]?.endsWith("sync-abi.ts")) {
  const out = render();
  const target = "lib/payroll-abi.ts";
  if (process.argv.includes("--check")) {
    const current = (() => {
      try {
        return readFileSync(target, "utf8");
      } catch {
        return "";
      }
    })();
    if (current !== out) {
      console.error(`${target} is out of date. Run: npx tsx scripts/sync-abi.ts`);
      process.exit(1);
    }
    console.log(`${target} is current.`);
  } else {
    writeFileSync(target, out);
    console.log(`Wrote ${target}`);
  }
}
