/**
 * THE WARRANT MARK'S GEOMETRY, generated by ~/projects/warrant-brand/mark.py. Do not edit:
 * change mark.py and run it, so the site, the X profile, the films and the files people are
 * sent all draw the same W.
 *
 * The W is two Vs. The first is solid: what has vested, theirs for good. The second is
 * engraved as an outline, filling from the bottom: what is vesting, every second. The fill is
 * the one accent. Filled outlines in a 100 x 100 box; draw VESTING with fill-rule evenodd,
 * then LEVEL in the accent, then VESTED in front.
 */
export const MARK_VIEWBOX = "0 0 100 100";
export const MARK_VESTED = "M 8.00 12.87 L 20.43 12.87 L 32.11 47.29 L 43.78 12.87 L 56.22 12.87 L 32.11 83.93 Z";
export const MARK_VESTING = "M 43.78 12.87 L 56.22 12.87 L 67.89 47.29 L 79.57 12.87 L 92.00 12.87 L 67.89 83.93 Z M 48.06 15.93 L 54.02 15.93 L 67.89 56.82 L 81.76 15.93 L 87.73 15.93 L 67.89 74.40 Z";
export const MARK_LEVEL = "M 64.73 47.51 L 67.89 56.82 L 71.05 47.51 L 77.02 47.51 L 67.89 74.40 L 58.77 47.51 Z";
export const MARK_CHANNEL = "M 48.06 15.93 L 54.02 15.93 L 67.89 56.82 L 81.76 15.93 L 87.73 15.93 L 67.89 74.40 Z";
